# Main dotbot configuration file
# This file orchestrates the entire installation process

- defaults:
    link:
      rel: true
      force: true
      create: true
    shell:
      stdin: true
      stdout: true
      stderr: true 

- link:
    # Shell configurations
    ~/.bashrc: dotfiles/.bashrc
    #~/.bash_profile: .config/bash/bash_profile
    #~/.profile: .config/bash/profile
    
    # Git configuration
    #~/.gitconfig: .config/git/gitconfig
    #~/.gitignore: .config/git/gitignore
    
    # Editor configurations
    #~/.config/nvim: .config/nvim
    #~/.vimrc: .config/nvim/init.vim
    
    # Terminal configurations
    #~/.config/tmux: .config/tmux
    #~/.tmux.conf: .config/tmux/tmux.conf
    
    # Other configurations
    #~/.config/alacritty: .config/alacritty
    #~/.config/kitty: .config/kitty
    
    # Cursor configurations
    ~/.cursor/mcp.json: dotfiles/.cursor/mcp.json

- shell:
    # Initialize git submodules
    - [git submodule update --init --recursive, Initializing submodules]
    
    # Run custom installation scripts
    - [bash scripts/install/install.sh, Running custom installation]
    
    # Set up shell
    #- [bash install/shell.sh, Setting up shell]
    
    # Install packages
    - [sudo apt-get update, Updating package lists]
    - [sudo apt-get install -y build-essential cmake git curl wget stow, Installing system packages]
    - [sudo apt-get install -y neovim tmux ripgrep fd-find git-extras, Installing development packages]
    - [sudo apt-get install -y alacritty kitty zsh htop tree, Installing terminal packages]
    #- [sudo apt-get install -y obsidian firefox vlc spotify-client, Installing optional packages]
    
    # Set up development tools
    #- [bash install/tools.sh, Setting up development tools]
    
    # Configure desktop environment
    #- [bash install/desktop.sh, Configuring desktop environment] 