# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = """
[╭─](bold blue)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$docker_context\
$kubernetes\
[╰─](bold blue)\
$character"""

# Disable the package module, hiding it from the prompt
[package]
disabled = true

# Use custom directory format
[directory]
style = "bold cyan"
read_only = " "
truncation_length = 3

# Customize the git branch format
[git_branch]
symbol = " "
style = "bold purple"

# Customize the git status format
[git_status]
style = "bold green"
format = '([\[$all_status$ahead_behind\] ]($style) )'

# Customize the nodejs version format
[nodejs]
format = "[$symbol($version )]($style)"
style = "bold green"
symbol = " "

# Customize the python version format
[python]
format = "[$symbol$version]($style)"
style = "bold yellow"
symbol = " "

# Customize the docker context format
[docker_context]
format = "[$symbol$context]($style)"
style = "bold blue"
symbol = " "

# Customize the kubernetes format
[kubernetes]
format = "[$symbol$context($namespace)]($style)"
style = "bold cyan"
symbol = " "

# Customize the character format
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

# Customize the username format
[username]
style_user = "bold blue"
style_root = "bold black"
show_always = true
disabled = false

# Customize the hostname format
[hostname]
ssh_only = true
format = "[@$hostname](bold red) "
disabled = false 